language: go
go:
  - 1.20.x

service:
  - docker

env:
  global:
    - USER="okpalaChidiebere"
    - DOCKER_USERNAME="aluminetchidiebre"
    - SERVICE_NAME="chirper-app-tweet-service"
    - GOPRIVATE="github.com/${USER}"

# Pre-testing installs
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > $HOME/.netrc # get user token from github here: https://github.com/settings/tokens/new
  - mkdir -vp $HOME/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > $HOME/.docker/cli-plugins/docker-buildx
  - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2 # documentation: https://golangci-lint.run/usage/quick-start/

install:
  - echo "nothing needs to be installed; skipping..."

# Scripts to be run such as tests
before_script:
  - echo "skipping before_script step..."

script:
  - golangci-lint run ./... --disable-all -E errcheck #ignore 'errcheck' lints
  - go test -v -race ./...

deploy:
  provider: script
  script: docker --version;
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    docker buildx build --secret id=gitcredentials,src=$HOME/.netrc -t "$DOCKER_USERNAME"/"$SERVICE_NAME":"$TRAVIS_BUILD_ID" --build-arg GOPRIVATE=$GOPRIVATE .;
    docker images;
    docker push "$DOCKER_USERNAME"/"$SERVICE_NAME":"$TRAVIS_BUILD_ID";
